### ISSUE TITLE
Please remove dependency on Servo Library

### ISSUE THREAD

**Issue by fraser125** [madhephaestus/WiiChuck#4]
I'm compiling the Wiichuck library for an ESP8266 and the Servo Library is not listed as compatible so my program doesn't compile. After removing the references, it at least compiles. Also it doesn't seem like the Servo feature was fully implemented. In removing the Servo Library I found a few other compiler errors that when fixed may improve the overall code quality.

I'll update once I've actually tested the library on the ESP8266.

**Comment by madhephaestus** [comment]
hmm, thats strange since the primary platform is the NodeMCU (an esp8266 with the USB breakout). Maybe 90% of expected use cases are mapping servos to buton/joy actions. making that the core use case does not imply we should remove that dependency, and the issue were having is not one i can reproduce on my system.
